-keep class com.rejeq.cpcam.core.stream.jni.FFmpegOutputJni { *; }
-keep class com.rejeq.cpcam.core.stream.jni.FFmpegVideoStreamJni { *; }
-keep class com.rejeq.cpcam.core.stream.jni.FFmpegVideoConfig { *; }
-keep class com.rejeq.cpcam.core.stream.jni.FFmpegPixFmt { *; }
